/** Generated by tools/figma/illustrations.mjs — do not edit by hand. */
export const creatives = {
  "logo-color": {
    "src": "/figma/creatives/logo-color.webp",
    "fallback": "/figma/creatives/logo-color.png",
    "width": 1495,
    "height": 179,
    "designWidth": 1494.59,
    "designHeight": 178.78,
    "alt": "Talentilo.ai"
  },
  "logo-color-on-dark": {
    "src": "/figma/creatives/logo-color-on-dark.webp",
    "fallback": "/figma/creatives/logo-color-on-dark.png",
    "width": 1495,
    "height": 179,
    "designWidth": 1494.59,
    "designHeight": 178.78,
    "alt": "Talentilo.ai"
  },
  "logo-mono-black": {
    "src": "/figma/creatives/logo-mono-black.webp",
    "fallback": "/figma/creatives/logo-mono-black.png",
    "width": 1495,
    "height": 179,
    "designWidth": 1494.59,
    "designHeight": 178.78,
    "alt": "Talentilo.ai"
  },
  "logo-mono-white": {
    "src": "/figma/creatives/logo-mono-white.webp",
    "fallback": "/figma/creatives/logo-mono-white.png",
    "width": 1495,
    "height": 179,
    "designWidth": 1494.59,
    "designHeight": 178.78,
    "alt": "Talentilo.ai"
  },
  "hero-command-center": {
    "src": "/figma/creatives/hero-command-center.webp",
    "fallback": "/figma/creatives/hero-command-center.png",
    "width": 2624,
    "height": 1300,
    "designWidth": 1312,
    "designHeight": 650,
    "alt": "Talentilo command centre dashboard"
  },
  "logo-bell": {
    "src": "/figma/creatives/logo-bell.webp",
    "fallback": "/figma/creatives/logo-bell.png",
    "width": 340,
    "height": 180,
    "designWidth": 170,
    "designHeight": 90,
    "alt": "Bell"
  },
  "logo-asana": {
    "src": "/figma/creatives/logo-asana.webp",
    "fallback": "/figma/creatives/logo-asana.png",
    "width": 340,
    "height": 180,
    "designWidth": 170,
    "designHeight": 90,
    "alt": "Asana"
  },
  "logo-sap": {
    "src": "/figma/creatives/logo-sap.webp",
    "fallback": "/figma/creatives/logo-sap.png",
    "width": 340,
    "height": 180,
    "designWidth": 170,
    "designHeight": 90,
    "alt": "SAP"
  },
  "logo-salesforce": {
    "src": "/figma/creatives/logo-salesforce.webp",
    "fallback": "/figma/creatives/logo-salesforce.png",
    "width": 342,
    "height": 180,
    "designWidth": 171,
    "designHeight": 90,
    "alt": "Salesforce"
  },
  "logo-notion": {
    "src": "/figma/creatives/logo-notion.webp",
    "fallback": "/figma/creatives/logo-notion.png",
    "width": 342,
    "height": 180,
    "designWidth": 171,
    "designHeight": 90,
    "alt": "Notion"
  },
  "semantic-matching": {
    "src": "/figma/creatives/semantic-matching.webp",
    "fallback": "/figma/creatives/semantic-matching.png",
    "width": 1242,
    "height": 834,
    "designWidth": 620.79,
    "designHeight": 416.81,
    "alt": "Semantic matching engine ranking 500+ profiles down to 3 perfect matches"
  },
  "velocity-index": {
    "src": "/figma/creatives/velocity-index.webp",
    "fallback": "/figma/creatives/velocity-index.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Agency Velocity Index dashboard"
  },
  "ao-testimonial": {
    "src": "/figma/creatives/ao-testimonial.webp",
    "fallback": "/figma/creatives/ao-testimonial.png",
    "width": 2624,
    "height": 1162,
    "designWidth": 1312,
    "designHeight": 581,
    "alt": "Customer testimonial"
  },
  "ro-testimonial": {
    "src": "/figma/creatives/ro-testimonial.webp",
    "fallback": "/figma/creatives/ro-testimonial.png",
    "width": 2624,
    "height": 1162,
    "designWidth": 1312,
    "designHeight": 581,
    "alt": "Customer testimonial"
  },
  "hv-engaging": {
    "src": "/figma/creatives/hv-engaging.webp",
    "fallback": "/figma/creatives/hv-engaging.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "AI voice agents engaging 500+ candidates"
  },
  "mg-card-bullhorn": {
    "src": "/figma/creatives/mg-card-bullhorn.webp",
    "fallback": "/figma/creatives/mg-card-bullhorn.png",
    "width": 960,
    "height": 640,
    "designWidth": 480,
    "designHeight": 320,
    "alt": "On-premises and cloud ATS deployments being retired"
  },
  "mg-card-zoho": {
    "src": "/figma/creatives/mg-card-zoho.webp",
    "fallback": "/figma/creatives/mg-card-zoho.png",
    "width": 960,
    "height": 640,
    "designWidth": 480,
    "designHeight": 320,
    "alt": "A small-business tool outgrown by enterprise-scale activity"
  },
  "mg-terminal": {
    "src": "/figma/creatives/mg-terminal.webp",
    "fallback": "/figma/creatives/mg-terminal.png",
    "width": 1592,
    "height": 1146,
    "designWidth": 796,
    "designHeight": 573,
    "alt": "The Talentilo translation layer mapping a legacy export"
  },
  "nf-shapes": {
    "src": "/figma/creatives/nf-shapes.webp",
    "fallback": "/figma/creatives/nf-shapes.png",
    "width": 686,
    "height": 280,
    "designWidth": 343.02,
    "designHeight": 140,
    "alt": ""
  },
  "ros-command-center": {
    "src": "/figma/creatives/ros-command-center.webp",
    "fallback": "/figma/creatives/ros-command-center.png",
    "width": 2148,
    "height": 1192,
    "designWidth": 1074.13,
    "designHeight": 595.84,
    "alt": "The Talentilo command centre showing a job pipeline across every hiring stage"
  },
  "ros-guardrails": {
    "src": "/figma/creatives/ros-guardrails.webp",
    "fallback": "/figma/creatives/ros-guardrails.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Operational guardrail alerts for SLA breaches, offers, AI matches and daily digests"
  },
  "ros-ingestion": {
    "src": "/figma/creatives/ros-ingestion.webp",
    "fallback": "/figma/creatives/ros-ingestion.png",
    "width": 2273,
    "height": 657,
    "designWidth": 1136.52,
    "designHeight": 328.47,
    "alt": "The Talentilo translation layer importing a legacy export into a structured candidate record"
  },
  "ros-view-owner": {
    "src": "/figma/creatives/ros-view-owner.webp",
    "fallback": "/figma/creatives/ros-view-owner.png",
    "width": 2624,
    "height": 1228,
    "designWidth": 1312,
    "designHeight": 614,
    "alt": "The owner view: annual revenue targets tracked per recruiter"
  },
  "ros-view-ops": {
    "src": "/figma/creatives/ros-view-ops.webp",
    "fallback": "/figma/creatives/ros-view-ops.png",
    "width": 2624,
    "height": 1228,
    "designWidth": 1312,
    "designHeight": 614,
    "alt": "The operations view: floor alerts, held-up CVs and offer accept rate"
  },
  "ros-view-recruiter": {
    "src": "/figma/creatives/ros-view-recruiter.webp",
    "fallback": "/figma/creatives/ros-view-recruiter.png",
    "width": 2624,
    "height": 1228,
    "designWidth": 1312,
    "designHeight": 614,
    "alt": "The recruiter view: a single candidate record with contact details and history"
  },
  "ti-hero-database": {
    "src": "/figma/creatives/ti-hero-database.webp",
    "fallback": "/figma/creatives/ti-hero-database.png",
    "width": 2148,
    "height": 1191,
    "designWidth": 1074.13,
    "designHeight": 595.25,
    "alt": "The Talentilo candidate database listing every profile with education, experience and skills"
  },
  "ti-recall": {
    "src": "/figma/creatives/ti-recall.webp",
    "fallback": "/figma/creatives/ti-recall.png",
    "width": 2624,
    "height": 1036,
    "designWidth": 1312,
    "designHeight": 518,
    "alt": "External search cost compared with Active Recall"
  },
  "offer-risk-alerts": {
    "src": "/figma/creatives/offer-risk-alerts.webp",
    "fallback": "/figma/creatives/offer-risk-alerts.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Offer management system flagging at-risk deals"
  },
  "ros-pending-review": {
    "src": "/figma/creatives/ros-pending-review.webp",
    "fallback": "/figma/creatives/ros-pending-review.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "A pending-review queue listing each job with its client and how long it has waited"
  },
  "hv-always-on": {
    "src": "/figma/creatives/hv-always-on.webp",
    "fallback": "/figma/creatives/hv-always-on.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Application volume through an overnight campaign launch, with AI capacity running the full height of every hour’s bar and headroom to spare above it"
  },
  "mg-transfer": {
    "src": "/figma/creatives/mg-transfer.webp",
    "fallback": "/figma/creatives/mg-transfer.png",
    "width": 2624,
    "height": 1120,
    "designWidth": 1312,
    "designHeight": 560,
    "alt": "One candidate record shown three times — in the old ATS, mid-move with every part of the record ticked off, and arrived in Talentilo with the same notes, submissions and tags intact"
  },
  "ti-boolean-legacy": {
    "src": "/figma/creatives/ti-boolean-legacy.webp",
    "fallback": "/figma/creatives/ti-boolean-legacy.png",
    "width": 960,
    "height": 640,
    "designWidth": 480,
    "designHeight": 320,
    "alt": "A Boolean keyword filter reading the same resume and finding neither search term written on it, so nothing matches"
  },
  "ti-boolean-semantic": {
    "src": "/figma/creatives/ti-boolean-semantic.webp",
    "fallback": "/figma/creatives/ti-boolean-semantic.png",
    "width": 960,
    "height": 640,
    "designWidth": 480,
    "designHeight": 320,
    "alt": "The semantic engine reading the same resume in context, taking Project Lead as Manager and Budget Owner as P&L exposure"
  },
  "ti-parser": {
    "src": "/figma/creatives/ti-parser.webp",
    "fallback": "/figma/creatives/ti-parser.png",
    "width": 2624,
    "height": 860,
    "designWidth": 1312,
    "designHeight": 430,
    "alt": "Three unstructured sources — a PDF resume, an email attachment and a CSV export — parsed into one structured candidate record"
  },
  "ro-governance": {
    "src": "/figma/creatives/ro-governance.webp",
    "fallback": "/figma/creatives/ro-governance.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Global compliance rules applied to local teams"
  },
  "ro-single-truth": {
    "src": "/figma/creatives/ro-single-truth.webp",
    "fallback": "/figma/creatives/ro-single-truth.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Disjointed tools unified into one flow"
  },
  "pc-guardrails": {
    "src": "/figma/creatives/pc-guardrails.webp",
    "fallback": "/figma/creatives/pc-guardrails.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Operational guardrails alerting leadership"
  },
  "pc-velocity": {
    "src": "/figma/creatives/pc-velocity.webp",
    "fallback": "/figma/creatives/pc-velocity.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Time-to-fill measured at every pipeline stage"
  },
  "ao-superstar": {
    "src": "/figma/creatives/ao-superstar.webp",
    "fallback": "/figma/creatives/ao-superstar.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Workflow intelligence held in the platform, not one recruiter"
  },
  "ao-margins": {
    "src": "/figma/creatives/ao-margins.webp",
    "fallback": "/figma/creatives/ao-margins.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Revenue per seat driving margin"
  },
  "ti-ranking": {
    "src": "/figma/creatives/ti-ranking.webp",
    "fallback": "/figma/creatives/ti-ranking.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Candidates scored 0–100% by contextual fit"
  },
  "tr-semantic": {
    "src": "/figma/creatives/tr-semantic.webp",
    "fallback": "/figma/creatives/tr-semantic.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Semantic matching across a real tech stack"
  },
  "tr-verify": {
    "src": "/figma/creatives/tr-verify.webp",
    "fallback": "/figma/creatives/tr-verify.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Candidates ranked by assessment pass rate"
  },
  "rd-notice-tracker": {
    "src": "/figma/creatives/rd-notice-tracker.webp",
    "fallback": "/figma/creatives/rd-notice-tracker.png",
    "width": 1176,
    "height": 1072,
    "designWidth": 588,
    "designHeight": 536,
    "alt": "Notice-period risk tracked candidate by candidate"
  }
} as const;

export type CreativeName = keyof typeof creatives;
