/** Generated by tools/figma/images.mjs — do not edit by hand. Keyed by Figma image hash. */
export const figmaImages = {
  "19e045a1319fe4a16c9e6fb45244dd8f31af19d3": {
    "src": "/figma/images/19e045a1319f.png",
    "width": 2680,
    "height": 2680,
    "webp": "/figma/images/19e045a1319f.webp"
  },
  "2f3ff23866f54c09473c12da8fca1cdaf6e98b2b": {
    "src": "/figma/images/2f3ff23866f5.png",
    "width": 112,
    "height": 112
  },
  "314902fc64e8d97d98ed5a69c66ff248b822ec2e": {
    "src": "/figma/images/314902fc64e8.jpg",
    "width": 1920,
    "height": 1280,
    "webp": "/figma/images/314902fc64e8.webp"
  },
  "3d81068413f1faecb4c870bb763d0dae05babf7d": {
    "src": "/figma/images/3d81068413f1.png",
    "width": 192,
    "height": 192
  },
  "3e55ebd74ceb11c37d8f6320cce5448fdf39d665": {
    "src": "/figma/images/3e55ebd74ceb.jpg",
    "width": 595,
    "height": 842,
    "webp": "/figma/images/3e55ebd74ceb.webp"
  },
  "6c652468288e770c845ef5aa877e4ead5e6b85db": {
    "src": "/figma/images/6c652468288e.jpg",
    "width": 1920,
    "height": 1280,
    "webp": "/figma/images/6c652468288e.webp"
  },
  "8b4fc046b6a14ec7293f0af2b03e2519cec94957": {
    "src": "/figma/images/8b4fc046b6a1.jpg",
    "width": 1920,
    "height": 1280,
    "webp": "/figma/images/8b4fc046b6a1.webp"
  },
  "8c2b5fbb0fbe6c0b5b9c1b517e80496229ceb11e": {
    "src": "/figma/images/8c2b5fbb0fbe.jpg",
    "width": 100,
    "height": 100
  },
  "a74c5943fc5b830f0a950f01b78d8bd9c0bb9691": {
    "src": "/figma/images/a74c5943fc5b.png",
    "width": 512,
    "height": 512,
    "webp": "/figma/images/a74c5943fc5b.webp"
  },
  "b8581a3a8f9a19b6eec05845c18e07081f487330": {
    "src": "/figma/images/b8581a3a8f9a.png",
    "width": 128,
    "height": 128
  },
  "bf56160bf500da99296cb6c1dfdab678bc5100cd": {
    "src": "/figma/images/bf56160bf500.png",
    "width": 513,
    "height": 513,
    "webp": "/figma/images/bf56160bf500.webp"
  },
  "d4cb6ba5aec1096538e21ef41e642380536d2cbd": {
    "src": "/figma/images/d4cb6ba5aec1.png",
    "width": 1280,
    "height": 601,
    "webp": "/figma/images/d4cb6ba5aec1.webp"
  },
  "da416245e6c0008541ebbaee04a05405e58598b7": {
    "src": "/figma/images/da416245e6c0.png",
    "width": 112,
    "height": 112
  },
  "ec7e98251a65c16dfc512a6037d1df3716459afd": {
    "src": "/figma/images/ec7e98251a65.png",
    "width": 515,
    "height": 515,
    "webp": "/figma/images/ec7e98251a65.webp"
  },
  "f840e3e9cc312d9cc3623addea67bdd715ac8046": {
    "src": "/figma/images/f840e3e9cc31.png",
    "width": 512,
    "height": 512,
    "webp": "/figma/images/f840e3e9cc31.webp"
  }
} as const;
